// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: accounting/service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Neo.FileStorage.API.Accounting {
  /// <summary>
  /// Accounting service provides methods for interaction with NeoFS sidechain via
  /// other NeoFS nodes to get information about the account balance. Deposit and
  /// Withdraw operations can't be implemented here, as they require Mainnet NeoFS
  /// smart contract invocation. Transfer operations between internal NeoFS
  /// accounts are possible, if both use the same token type.
  /// </summary>
  public static partial class AccountingService
  {
    static readonly string __ServiceName = "neo.fs.v2.accounting.AccountingService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Neo.FileStorage.API.Accounting.BalanceRequest> __Marshaller_neo_fs_v2_accounting_BalanceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Neo.FileStorage.API.Accounting.BalanceRequest.Parser));
    static readonly grpc::Marshaller<global::Neo.FileStorage.API.Accounting.BalanceResponse> __Marshaller_neo_fs_v2_accounting_BalanceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Neo.FileStorage.API.Accounting.BalanceResponse.Parser));

    static readonly grpc::Method<global::Neo.FileStorage.API.Accounting.BalanceRequest, global::Neo.FileStorage.API.Accounting.BalanceResponse> __Method_Balance = new grpc::Method<global::Neo.FileStorage.API.Accounting.BalanceRequest, global::Neo.FileStorage.API.Accounting.BalanceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Balance",
        __Marshaller_neo_fs_v2_accounting_BalanceRequest,
        __Marshaller_neo_fs_v2_accounting_BalanceResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Neo.FileStorage.API.Accounting.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AccountingService</summary>
    [grpc::BindServiceMethod(typeof(AccountingService), "BindService")]
    public abstract partial class AccountingServiceBase
    {
      /// <summary>
      /// Returns the amount of funds in GAS token for the requested NeoFS account.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Neo.FileStorage.API.Accounting.BalanceResponse> Balance(global::Neo.FileStorage.API.Accounting.BalanceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AccountingService</summary>
    public partial class AccountingServiceClient : grpc::ClientBase<AccountingServiceClient>
    {
      /// <summary>Creates a new client for AccountingService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AccountingServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AccountingService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AccountingServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AccountingServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AccountingServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Returns the amount of funds in GAS token for the requested NeoFS account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Neo.FileStorage.API.Accounting.BalanceResponse Balance(global::Neo.FileStorage.API.Accounting.BalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Balance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the amount of funds in GAS token for the requested NeoFS account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Neo.FileStorage.API.Accounting.BalanceResponse Balance(global::Neo.FileStorage.API.Accounting.BalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Balance, null, options, request);
      }
      /// <summary>
      /// Returns the amount of funds in GAS token for the requested NeoFS account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Neo.FileStorage.API.Accounting.BalanceResponse> BalanceAsync(global::Neo.FileStorage.API.Accounting.BalanceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BalanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the amount of funds in GAS token for the requested NeoFS account.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Neo.FileStorage.API.Accounting.BalanceResponse> BalanceAsync(global::Neo.FileStorage.API.Accounting.BalanceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Balance, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AccountingServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AccountingServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AccountingServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Balance, serviceImpl.Balance).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AccountingServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Balance, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Neo.FileStorage.API.Accounting.BalanceRequest, global::Neo.FileStorage.API.Accounting.BalanceResponse>(serviceImpl.Balance));
    }

  }
}
#endregion
